from setuptools import setup

setup(
    name='libdigitone',
    version='0.1',
    packages=['venv.lib.python3.7.site-packages.pip', 'venv.lib.python3.7.site-packages.pip._vendor',
              'venv.lib.python3.7.site-packages.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip._vendor.pep517',
              'venv.lib.python3.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip._internal', 'venv.lib.python3.7.site-packages.pip._internal.cli',
              'venv.lib.python3.7.site-packages.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip._internal.operations', 'venv.lib.python3.7.site-packages.mido',
              'venv.lib.python3.7.site-packages.mido.backends', 'venv.lib.python3.7.site-packages.mido.messages',
              'venv.lib.python3.7.site-packages.mido.midifiles', 'venv.lib.python3.7.site-packages.rtmidi',
              'libdigitone'],
    url='https://gitlab.com/dhuck/libdigitone',
    license='MIT',
    author='dhuck',
    author_email='d@tinycact.us',
    description='Portable library for interfacing with the Elektron Digitone'
)
